# Generated by Django 5.0.3 on 2024-03-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_des_contact_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
                ('order', models.CharField(max_length=22)),
                ('no', models.CharField(max_length=22)),
                ('date', models.DateField()),
            ],
        ),
    ]
